### ISSUE TITLE
Inconsistent name + suggestions

### ISSUE THREAD

**Issue by Mananite** [WatchTubeTeam/watchtubeteam.github.io#4]
**Inconsistent Name**
When i open the page/click Home the WatchTube name looks like this
![imagen](https://user-images.githubusercontent.com/88516116/170212950-b63e0ce9-1ccc-4502-bbf8-b687d3b33adb.png)

When i press Previous versions it looks like this
![imagen](https://user-images.githubusercontent.com/88516116/170213077-da3582f8-c981-4fef-a4bc-f067146a4f8e.png)

**Suggestions**
You could link TestFlight to the text that says textflight, looks a bit better (Previous versions)
![imagen](https://user-images.githubusercontent.com/88516116/170213312-384455d7-4864-4d99-98e3-9cc47f217f1a.png)

Replace With "What is WatchTube?" (Home)
![imagen](https://user-images.githubusercontent.com/88516116/170213539-cbbe08ca-f5c7-4cfb-a211-c4f0c2a2e8b8.png)

Replace Download and Textflight text with the download links, center the version, date and all that stuff (Home)
![imagen](https://user-images.githubusercontent.com/88516116/170214164-03d7d9f4-450a-4d32-bd2d-cd35d98dd8f4.png)

**Comment by 112cxyz** [comment]
Please Try Again With Extensions Disabled *it looks fine on mine

**Comment by Mananite** [comment]
i literally have no extensions in chrome

**Comment by 112cxyz** [comment]
firefox tho

**Comment by Mananite** [comment]
yeah tried in chrome too, same results

**Comment by Mananite** [comment]
![image](https://user-images.githubusercontent.com/88516116/170219303-9a168f23-101f-4e0d-9762-540b3a7f40e3.png)

![image](https://user-images.githubusercontent.com/88516116/170219319-01af69b6-fbd7-448e-bc39-84e5f06e047e.png)


![image](https://user-images.githubusercontent.com/88516116/170219267-beef954a-d47d-4321-b75b-69156ca57c75.png)

**Comment by 112cxyz** [comment]
I see i have contacted @CallMeEchoCodes to see what the hell its doing because it looks fine in code?

**Comment by Mananite** [comment]
Bottom of home is not broken in mobile
![image](https://user-images.githubusercontent.com/88516116/170220357-25534605-0f29-4c07-9492-f069b478ca17.png)

**Comment by Mananite** [comment]
i did not at any point close this

**Comment by 112cxyz** [comment]
Lmao thanks github. So the issue is nobody has added to the change log so now we just need to add that feature to hide if no changes

**Comment by 112cxyz** [comment]
![image](https://user-images.githubusercontent.com/78795456/170221651-fa2f84dd-b647-4270-b28f-ac47292163b8.png)
So there is a changelog the website is not grabbing it?

**Comment by Mananite** [comment]
it has the v1.4.1 thingy

**Comment by 112cxyz** [comment]
The dot is for the change log

**Comment by Mananite** [comment]
the dot is centered, the text is in the side
![image](https://user-images.githubusercontent.com/88516116/170222192-6b573561-8894-43fb-8824-f87b92948a61.png)

**Comment by Mananite** [comment]
doesnt have the changelog, for a split second it loads a version and changelog, then it doesnt.

**Comment by llsc12** [comment]
weird

**Comment by Mananite** [comment]
Yeah it’s weird as hell
